# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_team.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
conn = sqlite3.connect('cricket.db')
cur = conn.cursor()


class Ui_DeleteTeam(object):

    def del_team(self):
        cur.execute("select distinct Name from teams;")
        result = cur.fetchall()
        for t in result:
            self.del_combobox.addItem(t[0].replace("!", "'"))
            
        
    def setupUi(self, DeleteTeam):
        DeleteTeam.setObjectName("DeleteTeam")
        DeleteTeam.resize(320, 240)
        DeleteTeam.setStyleSheet("QDialog{\n"
                               "background-color:rgb(180, 180, 180)\n"
                               "}\n"
                               "QComboBox{\n"
                               "background-color:rgb(255, 255, 255)\n"
                               "}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DeleteTeam)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.del_label = QtWidgets.QLabel(DeleteTeam)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_label.setFont(font)
        self.del_label.setAlignment(QtCore.Qt.AlignCenter)
        self.del_label.setObjectName("del_label")
        self.verticalLayout_2.addWidget(self.del_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.del_combobox = QtWidgets.QComboBox(DeleteTeam)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_combobox.setFont(font)
        self.del_combobox.setObjectName("del_combobox")
        self.del_combobox.addItem("")
        self.verticalLayout.addWidget(self.del_combobox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.del_btn = QtWidgets.QPushButton(DeleteTeam)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_btn.setFont(font)
        self.del_btn.setObjectName("del_btn")
        self.verticalLayout.addWidget(self.del_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DeleteTeam)
        QtCore.QMetaObject.connectSlotsByName(DeleteTeam)

    def retranslateUi(self, DeleteTeam):
        _translate = QtCore.QCoreApplication.translate
        DeleteTeam.setWindowTitle(_translate("DeleteTeam", "Dialog"))
        self.del_label.setText(_translate("DeleteTeam", "Select Team to Delete"))
        self.del_combobox.setCurrentText(_translate("DeleteTeam", "Select Team"))
        self.del_combobox.setItemText(0, _translate("DeleteTeam", "Select Team"))
        self.del_btn.setText(_translate("DeleteTeam", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteTeam = QtWidgets.QDialog()
    ui = Ui_DeleteTeam()
    ui.setupUi(DeleteTeam)
    DeleteTeam.show()
    sys.exit(app.exec_())
